# Generated by Django 3.2.5 on 2021-07-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('especialidade', models.CharField(max_length=40)),
                ('crm', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_sus', models.CharField(max_length=20)),
                ('data_cadastro', models.DateField()),
                ('ultima_consulta', models.DateField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=9)),
                ('cep', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=20)),
                ('uf', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=20)),
                ('imagem', models.ImageField(blank=True, upload_to='prontuario/media')),
                ('sintomas', models.CharField(max_length=30)),
                ('medicacao', models.CharField(max_length=40)),
                ('diagnostico', models.CharField(max_length=100)),
                ('observacoes', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prontuario.consulta', verbose_name='Consulta')),
                ('exame', models.ManyToManyField(blank=True, to='prontuario.Exame')),
                ('medico', models.ManyToManyField(blank=True, to='prontuario.Medico')),
            ],
        ),
    ]
